config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  # root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/mentions-legales', to: 'pages#mentions_legales'


  # Lien vers formulaire de contact par email
  resources :contacts, only: [:new, :create]
  # Alternative to "resources"
  # get  "contacts/new", to: "contacts#new", as: :new_contact
  # post "contacts/new", to: "contacts#create"


  # creation et destroy de report_scope lors de la creation d'un projet
  resources :report_scope_orgas, only: [:destroy]

  # Vue sur la base ADEME
  resources :ademe_emission_factors, only: [:index]

  resources :reports do
    resources :report_scopes, except: :destroy
    resources :report_scope_orgas
    resources :report_scope_orga_users, only: [:index]
    # Route custom pour affichage du graphique
    get "results", to: "reports#result"
  end

  # Creation et edit de l'organisation d'une company
  resources :companies, only: [:show] do
    resources :orgas
  end

  resources :report_scopes, only: :destroy

  resources :report_scope_orgas, only: [] do
    get "send_report", to: "report_scope_orgas#send_report"
    # Route pour definir un email
    resources :report_scope_orga_users, only: [:new, :create, :destroy]
  end

  # Ajout ou edit d'un emission module
  resources :emission_modules, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :questions, only: [:new, :create, :destroy, :edit, :update]
  end

  # Test orga à plusieurs niveaux
  resources :testorgas, only: [:index]

  # Routes pour les articles
  resources :articles

  # Routes directes vers articles
  get '/ressources/reglementation_entreprise', to: 'articles#reglementation_entreprise'
  get '/ressources/comment_faire_son_bilan_carbone', to: 'articles#comment_faire_son_bilan_carbone'
  get '/ressources/scope_1_2_3', to: 'articles#scope_1_2_3'
  get '/ressources/pourquoi_faire_son_bilan_carbone', to: 'articles#pourquoi_faire_son_bilan_carbone'


  # Routes test pour emission_factor et activity_data
  get '/emission_factors', to: 'emission_factors#index'
  get '/fixed_energy', to: 'activity_data#fixed_energy'


  # Routes test dropdown dynamique
  # get 'welcome/index', to: "welcome#index"
  # get 'welcome/update_cities', as: 'update_cities'
  # get 'welcome/show'

  get 'welcome/update_artists', :as => 'update_artists'
  get 'welcome/update_songs', :as => 'update_songs'
  root :to => "welcome#index"


end

app/models/activity_datum.rb
class ActivityDatum < ApplicationRecord
    belongs_to :emission_factor

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :report_scope_orga
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :genre

  has_many :songs

  attr_accessible :genre_id, :name, :genre
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/business_unit.rb
aclass BusinessUnit < ApplicationRecord
  belongs_to :company
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :reports
  has_many :orgas

  include PgSearch::Model
  multisearchable against: [:name]
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,
    :presence => :true,
    :format => {
      :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
      :message => "must be a valid email address"
    }
  validates :message, :presence => :true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/emission_factor.rb
class EmissionFactor < ApplicationRecord
end

app/models/emission_module.rb
class EmissionModule < ApplicationRecord
  has_many :report_scopes
  has_many :questions
  has_one_attached :photo
end

app/models/genre.rb
class Genre < ApplicationRecord
  # attr_accessible :name

  has_many :artists
  has_many :songs, :through => :artists
end

app/models/orga.rb
class Orga < ApplicationRecord
  belongs_to :company
  has_many :report_scope_orgas
  has_many :report_scopes, through: :report_scope_orgas
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_orga,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :ademe_emission_factor
  belongs_to :emission_module
  has_many :answers
  has_many :report_scopes, through: :answers
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :company
  has_many :report_scopes, dependent: :destroy
  has_many :report_scope_orgas, through: :report_scopes
  has_many :orgas, through: :companies
  has_many :report_scope_orga_users, through: :users
  has_one_attached :photo, dependent: :destroy


  def report_scope_orga_users
    users = self.report_scopes.map do |report_scope|
      report_scope.report_scope_orgas.map do |report_scope_orga|
        report_scope_orga.report_scope_orga_users.map {|scope_orga_user| scope_orga_user.user}
      end
    end
    users.flatten.map { |user| user  }
  end

end

app/models/report_scope.rb
class ReportScope < ApplicationRecord
  belongs_to :report
  belongs_to :emission_module
  has_many :report_scope_orgas, dependent: :destroy
  has_many :orgas, through: :report_scope_orgas
  validates_uniqueness_of :report_id, scope: [:emission_module_id]

  def to_s
    emission_module.name
  end

end

app/models/report_scope_orga.rb
class ReportScopeOrga < ApplicationRecord
  belongs_to :orga
  belongs_to :report_scope
  has_many :emission_modules, through: :report_scope

  has_many :report_scope_orga_users, dependent: :destroy

  has_many :answers, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  # attr_accessible :artist_id, :title, :artist

end

app/models/testorga.rb
class Testorga < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company
  has_many :orgas, through: :company
  has_many :reports
  has_many :orgas, through: :company
  has_many :report_scopes, through: :reports
  has_many :report_scope_orga_users
  has_many :report_scope_orgas, through: :report_scope_orga_users

  has_one_attached :photo

  include PgSearch::Model
  multisearchable against: [
    :email,
    :first_name,
    :last_name,
    :job_position,
    :organization_position
  ]
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!,
                      only: [ :show,
                              :index,
                              :reglementation_entreprise,
                              :comment_faire_son_bilan_carbone,
                              :scope_1_2_3,
                              :pourquoi_faire_son_bilan_carbone]

  def index
    @articles = Article.all()
    render :layout => 'home'
  end

  def show
    @article = Article.find(params[:id])
    render :layout => 'home'
  end

  def reglementation_entreprise
    render :layout => 'home'
  end

  def comment_faire_son_bilan_carbone
    render :layout => 'home'
  end

  def scope_1_2_3
    render :layout => 'home'
  end

  def pourquoi_faire_son_bilan_carbone
    render :layout => 'home'
  end


  def new
    @article = Article.new()
    render :layout => 'home'
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to root_path
  end

  def edit
    @article = Article.find(params[:id])
    render :layout => 'home'
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to root_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    # no need for app/views
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :header, :text, :category, :author)
  end

end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
  end
end

app/views/articles/comment_faire_son_bilan_carbone.html.erb
<div class="bg-kc-lightblue py-5">
  <div class="container">
    <div class="row">
      <div class="col">
        <%= link_to "< Retour aux articles", articles_path, class:"btn btn-kc-outline-orange"  %>
        <!-- Titre -->
        <h1 class="my-4">
          Comment réaliser son bilan carbone ?
        </h1>
        <!-- Chapeau -->
        <p>
          Le bilan carbone, c’est une obligation réglementaire pour certaines
          entreprises, mais c’est surtout la première étape de sa stratégie bas-carbone.
          <br>
          Comment le réaliser pour faire de cet exercice un outil fédérateur
          et pas une simple collecte de données ? Suivez le guide !
        </p>
      </div>
    </div>
  </div>
</div>

<div class="bg-white py-5">
  <div class="container article">
    <div class="row justify-content-center mb-5">
        <!-- Paragraphe 1-->
        <!-- Titre fixed -->
        <div class="col-12 col-lg-8">
          <h4 class="bg-white">
            1. Nommer un responsable
          </h4>
        </div>

        <!-- Contenu -->
        <div class="col-12 col-md-8 col-lg-5">
          <p>
            Première étape : nommer un responsable en charge de la réalisation
            du bilan carbone.
            <br>
            Il devra piloter l’ensemble de l’exercice, notamment coordonner la
            collecte des données à travers l’entreprise et s’assurer que les
            bons leviers sont identifiés dans le plan d’action.
          </p>

          <p>
            Même dans le cas où vous êtes accompagnés par un bureau d’étude ou
            un cabinet de conseil, il est indispensable d’avoir un responsable
            en interne pour que votre entreprise s’approprie les résultats et
            puisse mettre en oeuvre le plan d’action.
          </p>
        </div>
        <div class="col-12 col-md-4 col-lg-3 pt-3">
          <div class="centered-image mb-1">
            <%= image_tag 'articles/comment-faire-bilan/I-want-you-bilan-carbone.png',
                class: "illustration-35vh",
                alt: "I want you to calculate my carbon footprint"
            %>
          </div>
        </div>


        <!-- Paragraphe 2-->
        <!-- Titre -->
        <div class="col-12 col-lg-8 pt-3">
<!--           <div class="divider">
          </div> -->
          <!-- <div class="second-sticky-header"> -->
          <h4 class="bg-white">
            2. Définir le périmètre et les contributeurs
          </h4>
          <!-- </div> -->

          <!-- Contenu -->
          <h5>
            2.a. Périmètre
          </h5>

          <p>
            Le bilan carbone fait l’inventaire des émissions sur une période
            et pour une organisation donnée.
            Il faut donc définir au préalable trois éléments :
          </p>

          <ol>
            <br>
            <li>
              Le <span class="bg-kc-lightblue text-kc-blue"><strong>périmètre
              organisationnel et géographique</strong></span> :
              <ul>
                <li>
                  Le bilan carbone couvre les émissions de votre entreprise
                  en <strong>France</strong>, et dans le monde pour les
                  entreprises soumises à l’obligation de reporting extra-financier.
                </li>
                <li>
                  Pour tout savoir sur le périmètre couvert selon la réglementation,
                  <a href="/ressources/reglementation_entreprise" class="blue-link">cet article</a>
                  est là pour vous.
                </li>
              </ul>
            </li>
            <br>
            <li>
              Les <span class="bg-kc-lightblue text-kc-blue"><strong>catégories
              et postes d’émissions</strong></span> :
              <ul>
                <li>
                  Un bilan carbone couvre obligatoirement les
                  <strong>émissions directes</strong> telles que les carburants
                  (scope 1) et et les <strong>émissions indirectes liées à
                  l’énergie</strong>, par exemple l’électricité (scope 2).
                </li>
                <li>
                  Il peut également couvrir les <strong><i>“postes significatifs"</i></strong>
                  pour les entreprises d’une certaines taille : les
                  <strong>émissions indirectes (scope 3)</strong> telles que
                  les achats ou le transports sont alors obligatoires
                  <br>
                  L’ADEME propose des <a href="https://bilans-ges.ademe.fr/fr/ressource/guide-sectoriel-list"
                  class="blue-link" target="_blank">guides sectoriels</a>
                  qui précisent quelles émissions doivent être couvertes par secteur.
                </li>
              </ul>
            </li>
            <li>
              La <span class="bg-kc-lightblue text-kc-blue"><strong>période de référence</strong></span> :
              typiquement, on prend l’exercice comptable précédent pour pouvoir
              s’appuyer sur les données de reporting existantes
            </li>
          </ol>

          <h5>2.b. Contributeurs</h5>

          <p>
            Sans contributeurs métiers, pas de bilan carbone!
            En effet, le responsable du bilan carbone n’a pas accès à toutes les
            données opérationnelles, et ne peut pas juger seul des actions les
            plus pertinentes à mettre en oeuvre.
          </p>

          <p>
            Pour une entreprise ou une filiale de taille moyenne, il faut
            typiquement mobiliser une dizaine de personnes, et bien plus pour
            les grands groupes : contrôle de gestion, achats, RH, services
            généraux, production, supply chain…
            La plupart des directions sont mobilisées.
          </p>

          <div class="centered-image">
            <%= image_tag 'articles/comment-faire-bilan/travolta.gif',
                class: "illustration",
                alt: "Responsable RSE perdu sans ses contributeurs"
            %>
            <div class="mt-3">
              <p><small><i>
                Responsable bilan carbone sans contributeurs métiers
              </i></small></p>
            </div>
          </div>
        </div>


        <!-- Paragraphe 3-->
        <!-- Titre -->
        <div class="col-12 col-lg-8 pt-3">
<!--           <div class="divider">
          </div> -->
          <!-- <div class="third-sticky-header"> -->
          <h4 class="bg-white">
            3. Collecter les données et calculer son empreinte
          </h4>
          <!-- </div> -->
          <!-- Contenus -->
          <p>
            Pour calculer l’empreinte carbone de son entreprise, il n’y a qu’une
            formule (simple !) à retenir :
          </p>

          <div class="text-center">
            <p>
              <span class="bg-kc-lightblue text-kc-blue"><strong>Donnée d’activité</strong></span>
                x
              <span class="bg-kc-lightblue text-kc-blue"><strong>Facteur d’émission</strong></span>
            </p>
          </div>

          <p>
            Par exemple, pour l’empreinte carbone de l’électricité consommée, on
            prend la consommation (en kWh) et on la multiplie par le facteur
            d’émission (en kgCO2/kWh) fourni par l’ADEME.
          </p>
          <p>
            Tous les facteurs d’émissions standards sont
            <a href="https://www.bilans-ges.ademe.fr/" class="blue-link" target="_blank">
            accessibles gratuitement sur le site de l’ADEME</a>,
            et bien sûr intégrés dans KarbonChain. Si vous avez des facteurs
            spécifiques, vous pouvez les ajouter pour gagner en précision.
          </p>
          <p>
            Pour les données d’activités, c’est là que les contributeurs sont
            clés : ce sont eux qui ont accès aux données dans l’entreprise et
            sauront les renseigner.
            Le travail de collecte pouvant être exigeant, il est important
            d'identifier rapidement les postes les plus importants et d'adapter
            l'effort de collecte en conséquence
          </p>

          <p>
            Dans la pratique, le dialogue entre les contributeurs et le
            responsable du bilan carbone est clé : il ne s’agit pas de juste
            fournir une donnée pour un calcul, mais s’assurer que la donnée
            reflète bien la réalité du terrain.
          </p>
        </div>


        <!-- Paragraphe 4.-->
        <!-- Titre -->
        <div class="col-12 col-lg-8 pt-3">
<!--           <div class="divider">
          </div> -->
          <!-- <div class="fourth-sticky-header"> -->
          <h4 class="bg-white">
            4. Définir un plan d’action
          </h4>
          <!--/di -->
          <!-- Contenus -->
          <p>
            Mesurer, c’est bien. Agir, c’est mieux. Le bilan carbone doit
            obligatoirement comprendre un plan d’action, et c’est typiquement
            pour la définition de ces actions que les cabinets de conseil
            peuvent être une aide précieuse.
          </p>

          <p>
            Voici <span class="bg-kc-lightblue text-kc-blue"><strong>quatre principes</strong></span> p
            our un plan de réduction d’émissions réussi :
          </p>
          <ol>
            <li>
              <span class="bg-kc-lightblue text-kc-blue"><strong>Prioriser les postes d’émissions</strong></span>
              les plus importants, même si cela peut être des postes d’émission
              plus complexes (ex: logistique, achats). Souvent, réduire ses
              émissions, c’est être plus efficace, donc faire des économies.
            </li>
            <li>
              <span class="bg-kc-lightblue text-kc-blue"><strong>Identifier un
              responsable métier pour chaque action.</strong></span> Car seul lui
              pourra porter l’action opérationnellement.
            </li>
            <li>
              <span class="bg-kc-lightblue text-kc-blue"><strong>Décliner en
              indicateur opérationnel</strong></span>
              chaque objectif de réduction. Par exemple :
              <ul>
                <li>
                  <i>“augmenter le taux de remplissage des camions de 10%”</i>,
                </li>
                <li>
                  <i>“mener des travaux d’isolation sur la moitié du parc immobilier”</i>,
                </li>
                <li>
                  <i>“diminuer la consommation d’énergie de nos produits de 10%”</i>,
                </li>
              </ul>
            </li>
            <li>
              <span class="bg-kc-lightblue text-kc-blue"><strong>Rendre compte
              de l’avancement</strong></span> à votre direction et communiquer
              en interne.
            </li>
          </ol>
        </div>

        <!-- Paragraphe 5-->
        <!-- Titre -->
        <div class="col-12 col-lg-8 pt-3">
<!--           <div class="divider">
          </div> -->
          <!-- <div class="fifth-sticky-header"-->
          <h4 class="t-3 bg-white">
            5. S'inscrire dans la durée
          </h4>
          <!-- div-->
          <!-- Contenu -->
          <p>
            Un bilan carbone n’est qu’une première étape pour réduire son
            empreinte carbone. De plus, c’est un exercice “impossible” à
            réaliser complètement : il y aura toujours des émissions indirectes
            difficiles à estimer, des données imprécises…
            <br>Mais cela n’empêche pas le bilan carbone d’aiguiller l’action!
          </p>
          <p>
            Il est donc important d’inscrire son bilan carbone dans une démarche
            de long-terme :
          </p>
          <ul>
            <li>
              Définir une approche avec les contributeurs pour
              <span class="bg-kc-lightblue text-kc-blue"><strong>collecter des
              données plus précises</strong></span>
            </li>
            <li>
              <span class="bg-kc-lightblue text-kc-blue"><strong>Étendre
              progressivement le périmètre des émissions analysées</strong></span>
              (notamment indirectes)
            </li>
            <li>
              <span class="bg-kc-lightblue text-kc-blue"><strong>Définir des
              process interne et s’outiller</strong></span> pour mieux collecter
              les données et suivre les progrès, idéalement en réalisant son bilan
              chaque anné
            </li>
          </ul>
        </div>

        <!-- box-conclusion -->
        <div class="col-12 col-lg-8 box-conclusion p-4">
<!--           <div class="box-left pb-3">
              <h5 class="text-center">
                Le plus
              </h5>
              <%= image_tag 'pages/home/landing-page/main-logo.png', class: "logo" %>
          </div> -->
          <div class="box-right">
            <p>
              Notre solution résout deux des principales limites des bilans
              carbones traditionnels :
            </p>
            <p class="pl-3">
              <i class="fas fa-calculator"></i>  La <span class="bg-kc-lightblue"><strong>
              collecte des données et les calculs de l’empreinte </strong></span>,
              que nous automatisons au maximum
            </p>
            <p class="pl-3">
              <i class="fas fa-tasks"></i>  <span class="bg-kc-lightblue"><strong>L’animation et le suivi du plan d’action</strong></span>,
              qui est totalement intégré à KarbonChain
            </p>
          </div>
        </div>


    </div>
  <%= link_to "< Retour aux articles", articles_path, class:"btn btn-kc-outline-blue"  %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="container">

  <h5>Modifier l'article</h5>

  <%= simple_form_for [ @article ] do |f| %>
    <%= f.input :title %>
    <%= f.input :header %>
    <%= f.input :text %>
    <%= f.input :category %>
    <%= f.input :author %>
    <%= f.submit "Publier la mise à jour", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/articles/index.html.erb
<div class="bg-kc-lightblue py-5">
  <div class="container">
    <div class="row">
      <div class="col">
        <!-- Titre -->
        <h1 class="my-4">
          Ressources
        </h1>
        <!-- Chapeau -->
        <p>
          Tous les articles, références et sources pour vous guider dans votre
          reporting et votre stratégie bas-carbone.
        </p>
      </div>
    </div>
  </div>
</div>


<div class="bg-white py-5">
  <div class="container">
    <div class="cards">

      <a href="/ressources/pourquoi_faire_son_bilan_carbone">
        <div class="card-article">
          <img
            src="https://images.pexels.com/photos/356079/pexels-photo-356079.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
            style="height: 30vh"
            alt="point d’interrogation"
          />
          <div class="card-article-infos">
            <h6>Pourquoi faire le bilan GES de son entreprise ?</h6>
            <p class="small">Vous n’êtes pas encore convaincu ? Voici les raisons de passer de l’intention à l’action.</p>
          </div>
        </div>
      </a>


      <a href="/ressources/reglementation_entreprise">
        <div class="card-article">
          <img
            src="https://images.unsplash.com/photo-1423592707957-3b212afa6733?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1789&q=80"
            style="height: 30vh"
            alt="reglementation bilan carbone entreprise"
          />
          <div class="card-article-infos">

            <h6>Quelle réglementation pour votre reporting carbone ?</h6>
            <p class="small">Tout ce que vous avez toujours voulu savoir sur la réglementation BEGES et DPEF.</p>
          </div>
        </div>
      </a>

      <a href="/ressources/comment_faire_son_bilan_carbone">
        <div class="card-article">
            <img
              src="https://images.unsplash.com/photo-1473772564351-202a22a93101?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=742&q=80"
              style="height: 30vh"
              alt="comment faire son bilan carbone"
            />
          <div class="card-article-infos">
            <h6>
              Comment réaliser son <br>bilan carbone ?
            </h6>
            <p class="small">
              Cinq étapes pour faire de son bilan carbone un outil fédérateur pour l'action.
            </p>
          </div>
        </div>
      </a>

      <a href="/ressources/scope_1_2_3">
        <div class="card-article">
            <img
              src="https://images.unsplash.com/photo-1544885353-f3e1da5bc721?ixlib=rb-1.2.1&auto=format&fit=crop&w=1288&q=80"
              style="height: 30vh"
              alt="comment faire son bilan carbone"
            />
          <div class="card-article-infos">
            <h6>
              Scopes 1, 2 et 3 : quel périmètre ? <br> comment les calculer ?
            </h6>
            <p class="small">
              Un scope ça va, c'est quand il y en a plusieurs que ça peut être compliqué...
            </p>
          </div>
        </div>
      </a>



    </div>


  <!--   <% @articles.each do |article| %>
      <div>
        <h3><%= link_to article.title, article_path(article), class:""  %></h3>
        <p><%= link_to "Edit", edit_article_path(article) %></p>
        <p><%= link_to "Delete", article_path(article), method: :delete %></p>
      </div>
    <% end %>
   -->
    <div class="row">
  <!--     <h1><%= link_to "Ajouter un article", new_article_path, class:"btn btn-primary"  %></h1>
   --></div>

    <%= link_to "< Retour à la page d'accueil", root_path, class:"btn btn-kc-outline-orange"  %>


  </div>
</div>

app/views/articles/new.html.erb
<div class="container">

  <h5>Ajoutez un article</h5>

  <%= simple_form_for [ @article ] do |f| %>
    <%= f.input :title, placeholder: "Titre", :class => "tinymce", :rows => 40, :cols => 120 %>
    <%= f.input :header %>
    <%= text_area_tag :text, "", :rows => 20, :cols => 120 %>
    <script type="text/javascript">
      tinyMCE.init({
        selector: 'textarea.text'
      });
    </script>
    <%= f.input :category %>
    <%= f.input :author %>
    <%= f.submit "Publier l'article", class: "btn btn-primary" %>


  <% end %>


</div>


<%= tinymce %>

app/views/articles/show.html.erb
<div class="container">

  <h1><%= @article.title %></h1>
  <h5>Par <%= @article.author %></h5>
  <h4><%= @article.header %></h4>
  <p><%= @article.text %></p>

  <h1><%= link_to "Retour à la liste des artices", articles_path, class:"btn btn-light"  %></h1>

</div>