config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  # root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/mentions-legales', to: 'pages#mentions_legales'


  # Lien vers formulaire de contact par email
  resources :contacts, only: [:new, :create]
  # Alternative to "resources"
  # get  "contacts/new", to: "contacts#new", as: :new_contact
  # post "contacts/new", to: "contacts#create"


  # creation et destroy de report_scope lors de la creation d'un projet
  resources :report_scope_orgas, only: [:destroy]

  # Vue sur la base ADEME
  resources :ademe_emission_factors, only: [:index]

  resources :reports do
    resources :report_scopes, except: :destroy
    resources :report_scope_orgas
    resources :report_scope_orga_users, only: [:index]
    # Route custom pour affichage du graphique
    get "results", to: "reports#result"
  end

  # Creation et edit de l'organisation d'une company
  resources :companies, only: [:show] do
    resources :orgas
  end

  resources :report_scopes, only: :destroy

  resources :report_scope_orgas, only: [] do
    get "send_report", to: "report_scope_orgas#send_report"
    # Route pour definir un email
    resources :report_scope_orga_users, only: [:new, :create, :destroy]
  end

  # Ajout ou edit d'un emission module
  resources :emission_modules, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :questions, only: [:new, :create, :destroy, :edit, :update]
  end

  # Test orga à plusieurs niveaux
  resources :testorgas, only: [:index]

  # Routes pour les articles
  resources :articles

  # Routes directes vers articles
  get '/ressources/reglementation_entreprise', to: 'articles#reglementation_entreprise'
  get '/ressources/comment_faire_son_bilan_carbone', to: 'articles#comment_faire_son_bilan_carbone'
  get '/ressources/scope_1_2_3', to: 'articles#scope_1_2_3'
  get '/ressources/pourquoi_faire_son_bilan_carbone', to: 'articles#pourquoi_faire_son_bilan_carbone'


  # Routes test pour emission_factor et activity_data
  get '/emission_factors', to: 'emission_factors#index'
  get '/fixed_energy', to: 'activity_data#fixed_energy'


  # Routes test dropdown dynamique
  # get 'welcome/index', to: "welcome#index"
  # get 'welcome/update_cities', as: 'update_cities'
  # get 'welcome/show'

  get 'welcome/update_artists', :as => 'update_artists'
  get 'welcome/update_songs', :as => 'update_songs'
  root :to => "welcome#index"


end

app/models/activity_datum.rb
class ActivityDatum < ApplicationRecord
    belongs_to :emission_factor

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :report_scope_orga
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :genre

  has_many :songs

  attr_accessible :genre_id, :name, :genre
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/business_unit.rb
aclass BusinessUnit < ApplicationRecord
  belongs_to :company
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :reports
  has_many :orgas

  include PgSearch::Model
  multisearchable against: [:name]
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,
    :presence => :true,
    :format => {
      :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
      :message => "must be a valid email address"
    }
  validates :message, :presence => :true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/emission_factor.rb
class EmissionFactor < ApplicationRecord
end

app/models/emission_module.rb
class EmissionModule < ApplicationRecord
  has_many :report_scopes
  has_many :questions
  has_one_attached :photo
end

app/models/genre.rb
class Genre < ApplicationRecord
  # attr_accessible :name

  has_many :artists
  has_many :songs, :through => :artists
end

app/models/orga.rb
class Orga < ApplicationRecord
  belongs_to :company
  has_many :report_scope_orgas
  has_many :report_scopes, through: :report_scope_orgas
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_orga,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :ademe_emission_factor
  belongs_to :emission_module
  has_many :answers
  has_many :report_scopes, through: :answers
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :company
  has_many :report_scopes, dependent: :destroy
  has_many :report_scope_orgas, through: :report_scopes
  has_many :orgas, through: :companies
  has_many :report_scope_orga_users, through: :users
  has_one_attached :photo, dependent: :destroy


  def report_scope_orga_users
    users = self.report_scopes.map do |report_scope|
      report_scope.report_scope_orgas.map do |report_scope_orga|
        report_scope_orga.report_scope_orga_users.map {|scope_orga_user| scope_orga_user.user}
      end
    end
    users.flatten.map { |user| user  }
  end

end

app/models/report_scope.rb
class ReportScope < ApplicationRecord
  belongs_to :report
  belongs_to :emission_module
  has_many :report_scope_orgas, dependent: :destroy
  has_many :orgas, through: :report_scope_orgas
  validates_uniqueness_of :report_id, scope: [:emission_module_id]

  def to_s
    emission_module.name
  end

end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  # attr_accessible :artist_id, :title, :artist

end

app/models/testorga.rb
class Testorga < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company
  has_many :orgas, through: :company
  has_many :reports
  has_many :orgas, through: :company
  has_many :report_scopes, through: :reports
  has_many :report_scope_orga_users
  has_many :report_scope_orgas, through: :report_scope_orga_users

  has_one_attached :photo

  include PgSearch::Model
  multisearchable against: [
    :email,
    :first_name,
    :last_name,
    :job_position,
    :organization_position
  ]
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
      © KarbonChain 2020. Tous droits réservés | <%= link_to "Mentions légales", mentions_legales_path%>
  </div>
</div>

app/views/shared/_modal-report-scope-orga.html.erb
<div class="modal fade" id="staticBackdrop<%= orga.name.gsub(" ", "") %>" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content width-form">
      <div class="modal-header width-form">
        <h5 class="modal-title" id="staticBackdropLabel">Add module(s)</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container width-form">
          <div class="form-post mt-0">
            <%= simple_form_for [@report, @report_scope_orga],
              html: {id: "new_report_scope_orga_#{orga.id}"} do |f| %>
              <div class="row">
                <%= f.association :orga, as: :radio_buttons,
                input_html: { value: orga.id, id: "report_scope_orga_orga_#{orga.id}" }, as: :hidden%>
              </div>
              <div class="row">
                <!-- afficher  -->
              <fieldset class="form-group check_boxes required report_scope_orga_report_scope">
                <% @report.report_scopes.each do |report_scope| %>
                   <div class="form-check">
                    <input class="form-check-input check_boxes required" type="checkbox" value="<%= report_scope.id %>" name="report_scope_orga[report_scope_id][]" id="report_scope_orga_report_scope_id_<%=orga.id %>_<%=report_scope.id %>">
                    <label class="form-check-label collection_check_boxes" for="report_scope_orga_report_scope_id_<%=orga.id %>_<%=report_scope.id %>" ><%= report_scope  %></label>
                  </div>
                <% end %>
              </fieldset>
                 <!-- input_html: { id: "report_scope_orga_report_scope_id_#{orga.id}_#{emission_module}" } -->
              </div>
                <!-- Inject categories here -->
              <div class="row">
                <%= f.submit "Save", class: "btn-lg btn-block btn-success text-white"  %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm sticky-top navbar-kc">
  <%= link_to root_path, class: "navbar-brand" do %>
      <%# image_tag 'logo-round.png' %>
      <%= image_tag "main-logo.png" %>
    <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars toggler-icon"></i>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Ressources", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Mes projects", reports_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
           <%# link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar_demo.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%# link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Notre solution", root_path(anchor: "solution"), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Ressources", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "À propos", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", new_contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item d-none">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_project-create-1.html.erb
<div class="container mt-2">
  <nav class="nav nav-pills nav-fill">
    <a class="nav-item nav-link active">☁︎  Emissions</a>
    <div class="arrow-right-selected"></div>
    <a class="nav-item nav-link"><i class="fas fa-sitemap"></i> Organization</a>
    <div class="arrow-right-not-selected"></div>
    <a class="nav-item nav-link"><i class="fas fa-user-plus"></i> Team</a>
    <div class="arrow-right-not-selected"></div>
  </nav>
</div>

app/views/shared/_project-create-2.html.erb
<div class="container mt-2">
  <nav class="nav nav-pills nav-fill">
    <a class="nav-item nav-link">☁︎  Emissions</a>
    <div class="arrow-right-not-selected"></div>
    <a class="nav-item nav-link active"><i class="fas fa-sitemap"></i> Organization</a>
    <div class="arrow-right-selected"></div>
    <a class="nav-item nav-link"><i class="fas fa-user-plus"></i> Team</a>
    <div class="arrow-right-not-selected"></div>
  </nav>
</div>

app/views/shared/_project-create-3.html.erb
<!-- <div class="container mt-2">
  <nav class="nav nav-pills nav-fill">
    <a class="nav-item nav-link">1. Module selection</a>
    <div class="arrow-right-not-selected"></div>
    <a class="nav-item nav-link">2. Organization</a>
    <div class="arrow-right-not-selected"></div>
    <a class="nav-item nav-link active">3. Contributors</a>
    <div class="arrow-right-selected"></div>
  </nav>
</div> -->

app/views/shared/_research_orga_report_scope.html.erb
  <!-- Modale pour ajout des contributeurs -->

<div class="col-3">
  <% if params[:report_scope].present? %>
    <div class="bg-white rounded shadow">
      <% if params[:report_scope].present? %>
      <!-- Definition modale -->
        <div id="addEmail">
          <div class="tab-headerV2 pl-2">
            <h3 class="text-center"><i class="fas fa-user-plus"></i> Add Business Unit</h3>
          </div>
        </div>
      <% end %>
      <div class="scroller-70vh">
        <% if params[:report_scope].present? %>
          <!-- Definition modale -->
          <div id="addOrga">
            <!-- Simple form barre de recherche-->
            <div class="mx-2 mt-2">
              <%= form_tag url_for(report_scope: params[:report_scope]), method: :get do %>
                <div class="input-group mb-3">
                  <%= text_field_tag :query, params[:query], class:"form-control", autofocus: true%>
                  <%= hidden_field_tag :report_scope, params[:report_scope]%>
                <div class="input-group mb-3">
                  <%#= submit_tag "", id:"loupe" %>
                </div>
              <% end %>
            </div>

            <!-- Display resultats de la recherche -->
            <% if params[:query].present? %>
              <%= simple_form_for [@report, @report_scope_orga] do |f| %>
                <%= f.input :report_scope_id,
                input_html: { value: params[:report_scope] }, as: :hidden%>
                <%= f.association :orga, as: :check_boxes, collection: @results %>
                <!-- Inject categories here -->
                <%#= f.submit "Add", class: "btn btn-success w-100 py-2 mt-2"  %>
              <% end %>
            <% else %>
              <%= simple_form_for [@report, @report_scope_orga] do |f| %>
                <%= f.input :report_scope_id,
                input_html: { value: params[:report_scope] }, as: :hidden%>
                <%= f.association :orga, as: :check_boxes,
                label: false %>
                <!-- Inject categories here -->
              <%#= f.submit "Add", class: "btn btn-success w-100 py-2 mt-2"  %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <% if params[:report_scope].present? %>
    <%= link_to "Next", report_report_scope_orga_users_path(params[:report_id]), class:"btn btn-primary w-100 py-2" %>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<!-- Bonne pratique pour déclarer @user? -->
<% @user = current_user %>

<div id="wrapper">
  <div id="sidebar-wrapper">
    <div class="menu-top">
      <%= link_to reports_path do %>
        <h5 class="mb-4">
          <%= "KarbonChain" %>
        </h5>
      <% end %>
      <%= image_tag "avatar_demo.jpg", class: "avatar-large mb-4", alt: "avatar-large" %>

      <!-- Reports avec collapse -->
      <div class="my-reports-collapse">
        <a class="pl-0" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
          <h5 class="menu-top-option">
            <%= image_tag "",class:"fas fa-folder text-primary mb-2 pr-3 pl-3" %>
            <%= "My reports" %>
          </h5>
        </a>
        <ul class="list-group text-left pl-4 mb-3">
          <div class="collapse" id="collapseExample">
            <li class="list-group pl-3">
              <%= link_to "Create new report",
                      "data-toggle" => "modal",
                      "data-target" => "#exampleModalCenter" do %>
                <p class="text-success"><i class="fas fa-plus-circle text-success"></i>
                <%= " New report" %></p>
              <% end %>
            </li>
            <% if @reports.nil? == false %>
              <% @reports.each do |report| %>
                <li class="list-group pl-3">
                  <%= link_to report_path(report.id)do %>
                    <p><i class="fas fa-file text-primary"></i>
                    <%= report.name %></p>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          </div>
        </ul>
      </div>

      <!-- My company -->
      <h5 class="menu-top-option mb-4">
        <%= image_tag "",class:"fas fa-building text-primary mb-2 pr-3 pl-3" %>
        <%= link_to "My company", company_path(@user.company) %>
      </h5>

      <!-- My messages -->
      <h5 class="menu-top-option mb-4">
        <%= image_tag "",class:"fas fa-envelope text-primary mb-1 pr-3 pl-3" %>
        <%= "My messages" %>
      </h5>

      <!-- Emissions -->
      <h5 class="menu-top-option mb-4">
        <%= image_tag "",class:"fas fa-cloud text-primary mb-1 pr-3 pl-3" %>
        <%= link_to "Emissions", emission_modules_path %>
      </h5>
    </div>

    <!-- Bottom links -->
    <div class="menu-bottom mb-2">
      <ul class="list-group">
        <li class="list-group mt-3">
          <%= link_to reports_path do %>
            <h5><i class="fas fa-life-ring text-primary pr-3 pl-3"></i>
            <%= " Support" %></h5>
          <% end %>
        </li>
        <li class="list-group mt-3">
          <%= link_to reports_path do %>
            <h5><i class="fas fa-cog text-primary pr-3 pl-3"></i>
            <%= " Settings" %></h5>
          <% end %>
        </li>
        <li class="list-group mt-3">
          <%= link_to reports_path do %>
            <h5><i class="fas fa-sign-out-alt pr-3 pl-3"></i>
            <%= " Log out"%></h5>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>