config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  # root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/mentions-legales', to: 'pages#mentions_legales'


  # Lien vers formulaire de contact par email
  resources :contacts, only: [:new, :create]
  # Alternative to "resources"
  # get  "contacts/new", to: "contacts#new", as: :new_contact
  # post "contacts/new", to: "contacts#create"


  # creation et destroy de report_scope lors de la creation d'un projet
  resources :report_scope_orgas, only: [:destroy]

  # Vue sur la base ADEME
  resources :ademe_emission_factors, only: [:index]

  resources :reports do
    resources :report_scopes, except: :destroy
    resources :report_scope_orgas
    resources :report_scope_orga_users, only: [:index]
    # Route custom pour affichage du graphique
    get "results", to: "reports#result"
  end

  # Creation et edit de l'organisation d'une company
  resources :companies, only: [:show] do
    resources :orgas
  end

  resources :report_scopes, only: :destroy

  resources :report_scope_orgas, only: [] do
    get "send_report", to: "report_scope_orgas#send_report"
    # Route pour definir un email
    resources :report_scope_orga_users, only: [:new, :create, :destroy]
  end

  # Ajout ou edit d'un emission module
  resources :emission_modules, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :questions, only: [:new, :create, :destroy, :edit, :update]
  end

  # Test orga à plusieurs niveaux
  resources :testorgas, only: [:index]

  # Routes pour les articles
  resources :articles

  # Routes directes vers articles
  get '/ressources/reglementation_entreprise', to: 'articles#reglementation_entreprise'
  get '/ressources/comment_faire_son_bilan_carbone', to: 'articles#comment_faire_son_bilan_carbone'
  get '/ressources/scope_1_2_3', to: 'articles#scope_1_2_3'
  get '/ressources/pourquoi_faire_son_bilan_carbone', to: 'articles#pourquoi_faire_son_bilan_carbone'


  # Routes test pour emission_factor et activity_data
  get '/emission_factors', to: 'emission_factors#index'
  get '/fixed_energy', to: 'activity_data#fixed_energy'


  # Routes test dropdown dynamique
  # get 'welcome/index', to: "welcome#index"
  # get 'welcome/update_cities', as: 'update_cities'
  # get 'welcome/show'

  get 'welcome/update_artists', :as => 'update_artists'
  get 'welcome/update_songs', :as => 'update_songs'
  root :to => "welcome#index"


end

app/models/activity_datum.rb
class ActivityDatum < ApplicationRecord
    belongs_to :emission_factor

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :report_scope_orga
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :genre

  has_many :songs

  attr_accessible :genre_id, :name, :genre
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/business_unit.rb
aclass BusinessUnit < ApplicationRecord
  belongs_to :company
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :reports
  has_many :orgas

  include PgSearch::Model
  multisearchable against: [:name]
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,
    :presence => :true,
    :format => {
      :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
      :message => "must be a valid email address"
    }
  validates :message, :presence => :true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/emission_factor.rb
class EmissionFactor < ApplicationRecord
end

app/models/emission_module.rb
class EmissionModule < ApplicationRecord
  has_many :report_scopes
  has_many :questions
  has_one_attached :photo
end

app/models/genre.rb
class Genre < ApplicationRecord
  # attr_accessible :name

  has_many :artists
  has_many :songs, :through => :artists
end

app/models/orga.rb
class Orga < ApplicationRecord
  belongs_to :company
  has_many :report_scope_orgas
  has_many :report_scopes, through: :report_scope_orgas
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_orga,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :ademe_emission_factor
  belongs_to :emission_module
  has_many :answers
  has_many :report_scopes, through: :answers
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :company
  has_many :report_scopes, dependent: :destroy
  has_many :report_scope_orgas, through: :report_scopes
  has_many :orgas, through: :companies
  has_many :report_scope_orga_users, through: :users
  has_one_attached :photo, dependent: :destroy


  def report_scope_orga_users
    users = self.report_scopes.map do |report_scope|
      report_scope.report_scope_orgas.map do |report_scope_orga|
        report_scope_orga.report_scope_orga_users.map {|scope_orga_user| scope_orga_user.user}
      end
    end
    users.flatten.map { |user| user  }
  end

end

app/models/report_scope.rb
class ReportScope < ApplicationRecord
  belongs_to :report
  belongs_to :emission_module
  has_many :report_scope_orgas, dependent: :destroy
  has_many :orgas, through: :report_scope_orgas
  validates_uniqueness_of :report_id, scope: [:emission_module_id]

  def to_s
    emission_module.name
  end

end

app/models/report_scope_orga.rb
class ReportScopeOrga < ApplicationRecord
  belongs_to :orga
  belongs_to :report_scope
  has_many :emission_modules, through: :report_scope

  has_many :report_scope_orga_users, dependent: :destroy

  has_many :answers, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  # attr_accessible :artist_id, :title, :artist

end

app/models/testorga.rb
class Testorga < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company
  has_many :orgas, through: :company
  has_many :reports
  has_many :orgas, through: :company
  has_many :report_scopes, through: :reports
  has_many :report_scope_orga_users
  has_many :report_scope_orgas, through: :report_scope_orga_users

  has_one_attached :photo

  include PgSearch::Model
  multisearchable against: [
    :email,
    :first_name,
    :last_name,
    :job_position,
    :organization_position
  ]
end

app/controllers/emission_modules_controller.rb
class EmissionModulesController < ApplicationController

  def index
    @emission_modules = EmissionModule.all

    # affichage side bar
    @sidebar_show = true
  end

  def show
    @emission_module = EmissionModule.find(params[:id])

    # affichage side bar
    @sidebar_show = true
  end

  def new
    @emission_module = EmissionModule.new

    # affichage side bar
    @sidebar_show = true
  end

  def create
    @emission_module = EmissionModule.new(emission_module_params)
    @emission_module.save
    redirect_to emission_modules_path
  end

  def edit
    @emission_module = EmissionModule.find(params[:id])

    # affichage side bar
    @sidebar_show = true
  end

  def update
    @emission_module = EmissionModule.find(params[:id])
    @emission_module.update(emission_module_params)
    redirect_to emission_modules_path
  end

  def destroy
    @emission_module = EmissionModule.find(params[:id])
    @emission_module.destroy
    redirect_to emission_modules_path
  end

  private

  def emission_module_params
    params.require(:emission_module).permit(:name, :scope)
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
  end
end

app/views/emission_modules/edit.html.erb
<div class="container">

  <h5>Edit the emission type</h5>

  <%= simple_form_for [ @emission_module ] do |f| %>
    <%= f.input :name %>
    <%= f.input :scope %>
    <%= f.submit "Edit the emission name and scope", class: "btn btn-primary" %>
  <% end %>

  <!-- Simple form avec également questions -->

  <div class="row">
    <div class="col-8">
      <p>Question</p>
    </div>
    <div class="col-4">
      <p>Emission factor</p>
    </div>
  </div>

  <% @emission_module.questions.each do |question| %>
    <div class="row">
    <div class="col-8">
      <p><%= question.ademe_emission_factor.name %></p>
    </div>
    <div class="col-4">
      <p><%= question.ademe_emission_factor.emission_value %> <%= question.ademe_emission_factor.unit %></p>
    </div>
  </div>
  <% end %>

  <%= link_to " Add a question",
              new_emission_module_question_path(@emission_module),
              class:"btn btn-secondary" %>
</div>

app/views/emission_modules/index.html.erb
<!-- TO DO -->
<!-- disposition et background image -->


<div class="container">
  <h5>Emission types</h5>

  <!-- Add button-->
  <%= link_to "Add an emission type", new_emission_module_path, class:"btn btn-secondary" %>

  <!-- Scope 1 -->
  <h6>Scope 1</h6>

  <ul>
    <% @emission_modules.each do |emission_module| %>
      <% if emission_module.scope == "1" %>
        <div class="">
          <li>
          <p>
            <%= link_to "#{emission_module.name}",
                        emission_module_path(emission_module) %>
            <%= link_to "Edit",
                        edit_emission_module_path(emission_module),
                        class:"btn btn-secondary" %>
            - <%= link_to "Delete",
            emission_module_path(emission_module),
            method: :delete,
            data: { confirm: "Are you sure?" },
            class:"btn btn-warning" %>
          </p>
          </li>
        </div>
      <% end %>
    <% end %>
  </ul>

  <!-- Scope 2 -->
  <h6>Scope 2</h6>

  <ul>

  <% @emission_modules.each do |emission_module| %>
    <% if emission_module.scope == "2" %>
      <div class="">
        <li>
          <p>
            <%= link_to "#{emission_module.name}",
                        emission_module_path(emission_module) %>
            <%= link_to "Edit",
                        edit_emission_module_path(emission_module),
                        class:"btn btn-secondary" %>
            - <%= link_to "Delete",
            emission_module_path(emission_module),
            method: :delete,
            data: { confirm: "Are you sure?" },
            class:"btn btn-warning" %>
          </p>
        </li>
      </div>
    <% end %>
  <% end %>
  </ul>

  <!-- Scope 3 -->
  <h6>Scope 3</h6>
  <ul>
    <% @emission_modules.each do |emission_module| %>
      <% if emission_module.scope == "3" %>
        <div class="">
          <li>
          <p>
            <%= link_to "#{emission_module.name}",
                        emission_module_path(emission_module) %>
            <%= link_to "Edit",
                        edit_emission_module_path(emission_module),
                        class:"btn btn-secondary" %>            - <%= link_to "Delete",
            emission_module_path(emission_module),
            method: :delete,
            data: { confirm: "Are you sure?" },
            class:"btn btn-warning" %>
          </p>
          </li>
        </div>
      <% end %>
    <% end %>
  </ul>

</div>

app/views/emission_modules/new.html.erb
<div class="container">

  <h5>Add a new emission type</h5>

  <%= simple_form_for [ @emission_module ] do |f| %>
    <%= f.input :name %>
    <%= f.input :scope %>
    <%= f.submit "Add the emission type", class: "btn btn-primary" %>
  <% end %>

  <!-- Simple form avec également questions -->

  <p>Questions</p>

</div>

app/views/emission_modules/show.html.erb
<div class="container">

  <h5><%= @emission_module.name %></h5>

  <!-- Simple form avec également questions -->

  <div class="row">
    <div class="col-8">
      <p>Question</p>
    </div>
    <div class="col-4">
      <p>Emission factor</p>
    </div>
  </div>

  <% @emission_module.questions.each do |question| %>
    <div class="row">
    <div class="col-8">
      <p><%= question.ademe_emission_factor.name %></p>
      <%= link_to "edit",
          emission_module_question_path(@emission_module, question),
          method: :patch %>
    </div>
    <div class="col-4">
      <p><%= question.ademe_emission_factor.emission_value %> <%= question.ademe_emission_factor.unit %></p>
    </div>
  </div>
  <% end %>

  <%= link_to "Add a question",
              new_emission_module_question_path(@emission_module),
              class:"btn btn-secondary" %>
</div>