config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  devise_for :users
  # root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/mentions-legales', to: 'pages#mentions_legales'


  # Lien vers formulaire de contact par email
  resources :contacts, only: [:new, :create]
  # Alternative to "resources"
  # get  "contacts/new", to: "contacts#new", as: :new_contact
  # post "contacts/new", to: "contacts#create"


  # creation et destroy de report_scope lors de la creation d'un projet
  resources :report_scope_orgas, only: [:destroy]

  # Vue sur la base ADEME
  resources :ademe_emission_factors, only: [:index]

  resources :reports do
    resources :report_scopes, except: :destroy
    resources :report_scope_orgas
    resources :report_scope_orga_users, only: [:index]
    # Route custom pour affichage du graphique
    get "results", to: "reports#result"
  end

  # Creation et edit de l'organisation d'une company
  resources :companies, only: [:show] do
    resources :orgas
  end

  resources :report_scopes, only: :destroy

  resources :report_scope_orgas, only: [] do
    get "send_report", to: "report_scope_orgas#send_report"
    # Route pour definir un email
    resources :report_scope_orga_users, only: [:new, :create, :destroy]
  end

  # Ajout ou edit d'un emission module
  resources :emission_modules, only: [:index, :show, :new, :create, :destroy, :edit, :update] do
    resources :questions, only: [:new, :create, :destroy, :edit, :update]
  end

  # Test orga à plusieurs niveaux
  resources :testorgas, only: [:index]

  # Routes pour les articles
  resources :articles

  # Routes directes vers articles
  get '/ressources/reglementation_entreprise', to: 'articles#reglementation_entreprise'
  get '/ressources/comment_faire_son_bilan_carbone', to: 'articles#comment_faire_son_bilan_carbone'
  get '/ressources/scope_1_2_3', to: 'articles#scope_1_2_3'
  get '/ressources/pourquoi_faire_son_bilan_carbone', to: 'articles#pourquoi_faire_son_bilan_carbone'


  # Routes test pour emission_factor et activity_data
  get '/emission_factors', to: 'emission_factors#index'
  get '/fixed_energy', to: 'activity_data#fixed_energy'


  # Routes test dropdown dynamique
  # get 'welcome/index', to: "welcome#index"
  # get 'welcome/update_cities', as: 'update_cities'
  # get 'welcome/show'

  get 'welcome/update_artists', :as => 'update_artists'
  get 'welcome/update_songs', :as => 'update_songs'
  root :to => "welcome#index"


end

app/models/activity_datum.rb
class ActivityDatum < ApplicationRecord
    belongs_to :emission_factor

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :report_scope_orga
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :genre

  has_many :songs

  attr_accessible :genre_id, :name, :genre
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/business_unit.rb
aclass BusinessUnit < ApplicationRecord
  belongs_to :company
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
  has_many :reports
  has_many :orgas

  include PgSearch::Model
  multisearchable against: [:name]
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,
    :presence => :true,
    :format => {
      :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
      :message => "must be a valid email address"
    }
  validates :message, :presence => :true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/emission_factor.rb
class EmissionFactor < ApplicationRecord
end

app/models/emission_module.rb
class EmissionModule < ApplicationRecord
  has_many :report_scopes
  has_many :questions
  has_one_attached :photo
end

app/models/genre.rb
class Genre < ApplicationRecord
  # attr_accessible :name

  has_many :artists
  has_many :songs, :through => :artists
end

app/models/orga.rb
class Orga < ApplicationRecord
  belongs_to :company
  has_many :report_scope_orgas
  has_many :report_scopes, through: :report_scope_orgas
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_orga,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :ademe_emission_factor
  belongs_to :emission_module
  has_many :answers
  has_many :report_scopes, through: :answers
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  belongs_to :company
  has_many :report_scopes, dependent: :destroy
  has_many :report_scope_orgas, through: :report_scopes
  has_many :orgas, through: :companies
  has_many :report_scope_orga_users, through: :users
  has_one_attached :photo, dependent: :destroy


  def report_scope_orga_users
    users = self.report_scopes.map do |report_scope|
      report_scope.report_scope_orgas.map do |report_scope_orga|
        report_scope_orga.report_scope_orga_users.map {|scope_orga_user| scope_orga_user.user}
      end
    end
    users.flatten.map { |user| user  }
  end

end

app/models/report_scope.rb
class ReportScope < ApplicationRecord
  belongs_to :report
  belongs_to :emission_module
  has_many :report_scope_orgas, dependent: :destroy
  has_many :orgas, through: :report_scope_orgas
  validates_uniqueness_of :report_id, scope: [:emission_module_id]

  def to_s
    emission_module.name
  end

end

app/models/report_scope_orga.rb
class ReportScopeOrga < ApplicationRecord
  belongs_to :orga
  belongs_to :report_scope
  has_many :emission_modules, through: :report_scope

  has_many :report_scope_orga_users, dependent: :destroy

  has_many :answers, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  # attr_accessible :artist_id, :title, :artist

end

app/models/testorga.rb
class Testorga < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company
  has_many :orgas, through: :company
  has_many :reports
  has_many :orgas, through: :company
  has_many :report_scopes, through: :reports
  has_many :report_scope_orga_users
  has_many :report_scope_orgas, through: :report_scope_orga_users

  has_one_attached :photo

  include PgSearch::Model
  multisearchable against: [
    :email,
    :first_name,
    :last_name,
    :job_position,
    :organization_position
  ]
end

app/controllers/report_scopes_controller.rb
class ReportScopesController < ApplicationController

  def index
    @reports = Report.all
    @report = Report.find(params[:report_id])

    @module_scopes = EmissionModule.all
    @report_scopes = ReportScope.all
    @report_scope = ReportScope.new

    @project_create_1_nav = true

    # affichage side bar
    @sidebar_show = true

  end

  def create
    @module_scopes = EmissionModule.all
    @report_scope = ReportScope.new(report_scope_params)
    @report = Report.find(params[:report_id])
    @report_scope.report = @report
    @report_scope.save
    respond_to do |format|
      format.html { redirect_to report_report_scopes_path(@report_scope.report_id, tab_name: params[:tab_name]) }
      format.js
    end
  end

  def destroy
    @module_scopes = EmissionModule.all
    @report_scope = ReportScope.find(params[:id])
    @report = @report_scope.report
    @report_scope.destroy
    respond_to do |format|
      format.html { redirect_to report_report_scopes_path(@report_scope.report_id) }
      format.js
    end
  end

  private

  def report_scope_params
     params.require(:report_scope).permit(:emission_module_id)
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
  end
end

app/views/report_scopes/_report-scope-add-to-cart.html.erb
<div class="selected-modules">
  <% @module_scopes.each do |module_scope| %>
    <% if ReportScope.new(emission_module_id: module_scope.id, report_id: params[:report_id]).valid? == false %>
        <div class="flash-module-mini">
          <div class="flash-module-mini-info">
            <p class="card-title"><%= module_scope.name %></p>
          </div>
          <% report_scope = @report.report_scopes.find_by(emission_module_id: module_scope.id) %>
            <%= link_to "➖",
            report_scope_path(report_scope, report_id: params[:report_id]),
            method: :delete, class:"flash-module-mini-info-minus", remote: true %>
        </div>
    <% end %>
  <% end %>
  <% if @report.report_scopes.empty? %>
    <p class="text-center">Please add an emission type</p>
  <% else %>
    <p></p>
  <% end %>
</div>

app/views/report_scopes/_report-scope-create.html.erb
  <!-- Laurent edit - modale avec preview du contenu -->

  <%# link_to '#',  "data-toggle" => "modal", "data-target" => "#exampleModalCenter" do %>
    <div id="<%= module_scope.id %>" class="flash-module flash-module-unselected">
      <%= simple_form_for [report, report_scope], remote: true do |f| %>
        <%= f.input :emission_module_id, input_html: { value: module_scope.id }, as: :hidden %>
        <%= hidden_field_tag :tab_name, 'scope1-tab' %>
        <%= f.submit "#{module_scope.name}", class: "bg-transparent border-0 full-size-click text-center" %>
      <% end %>
    </div>
    <%# end %>

<!-- SI ON VEUT METTRE UNE PHOTO DERIERE CHAQUE EMISSION TYPE -->
<!-- <div id="<%#= module_scope.id %>" class="flash-module flash-module-unselected" style="background-image: url('<%#= module_scope.photo_url %>')"> -->

app/views/report_scopes/_report-scope-destroy.html.erb
<div id="<%= module_scope.id %>" class="row flash-module flash-module-selected">
    <%= link_to "#{module_scope.name}",
    report_scope_path(module_scope.report_scopes.first, report_id: params[:report_id] ),
    method: :delete, remote: true, class: "bg-transparent border-0 full-size-click text-center" %>
</div>

app/views/report_scopes/_report-scope-next-step.html.erb
<div id="next-step">
  <% if @report.report_scopes.empty? %>
    <p></p>
  <% else %>
    <%= link_to "Next", new_report_report_scope_orga_path(@report), class:"btn btn-primary btn-next" %>
  <% end %>
</div>

app/views/report_scopes/create.js.erb
function refreshCard(innerHTML) {
  const card = document.getElementById("<%= @report_scope.emission_module.id %>");
  card.outerHTML = innerHTML;
}

function addCard(innerHTML) {
// trouver la liste des cartes
const shoppingCart = document.querySelector(".selected-modules");
// inserer la carte du report scope cree
shoppingCart.outerHTML = innerHTML;
}

function addNext(innerHTML) {
const nextButton = document.getElementById("next-step");
nextButton.outerHTML = innerHTML;
}

refreshCard('<%= j render "report-scope-destroy", module_scope: @report_scope.emission_module %>')
addCard('<%= j render "report-scope-add-to-cart" %>')
addNext('<%= j render "report-scope-next-step" %>')

app/views/report_scopes/destroy.js.erb
function refreshCard(innerHTML) {
  const card = document.getElementById("<%= @report_scope.emission_module.id %>");
  card.outerHTML = innerHTML;
}

function addCard(innerHTML) {
// trouver la liste des cartes
const shoppingCart = document.querySelector(".selected-modules");
// inserer la carte du report scope cree
shoppingCart.outerHTML = innerHTML;
}


function addNext(innerHTML) {
const nextButton = document.getElementById("next-step");
nextButton.outerHTML = innerHTML;
}

refreshCard('<%= j render "report-scope-create", module_scope: @report_scope.emission_module, report: @report, report_scope: ReportScope.new %>')
addCard('<%= j render "report-scope-add-to-cart" %>')
addNext('<%= j render "report-scope-next-step" %>')

app/views/report_scopes/index.html.erb
<div class="container">
  <div class="">
    <nav class="nav nav-pills nav-fill">
      <a class="nav-item nav-link active mt-2">☁︎  Emissions</a>
      <div class="arrow-right-selected mt-2"></div>
      <a class="nav-item nav-link mt-2"><i class="fas fa-sitemap"></i> Organization</a>
      <div class="arrow-right-not-selected  mt-2"></div>
      <a class="nav-item nav-link mt-2"><i class="fas fa-user-plus"></i> Team</a>
      <div class="arrow-right-not-selected mt-2"></div>
    </nav>
  </div>
</div>

<div class="container">

  <div class="form-modules">
    <div class="form-modules-intro">
      <h4 class="">Please select your emission types</h4>
    </div>
    <div class="form-modules-content">
      <div class="form-list-modules">

        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="scope1-tab" data-toggle="tab" href="#scope1" role="tab" aria-controls="scope1" aria-selected="true">Direct emissions</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="scope2-tab" data-toggle="tab" href="#scope2" role="tab" aria-controls="scope2" aria-selected="false">Indirect emissions</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="scope3-tab" data-toggle="tab" href="#scope3" role="tab" aria-controls="scope3" aria-selected="false">Induced emissions</a>
          </li>
        </ul>
        <div class="list-modules-container">
          <div class="tab-content" id="myTabContent">
            <!--Scope 1 -->
            <div class="tab-pane fade show active" id="scope1" role="tabpanel" aria-labelledby="scope1-tab">
              <div class="flash-modules">
                <% @module_scopes.where(scope: 1).each do |module_scope1| %>
                  <% if ReportScope.new(emission_module_id: module_scope1.id, report_id: params[:report_id]).valid? %>
                    <%= render "report-scope-create", module_scope: module_scope1, report: @report, report_scope: @report_scope%>
                  <% else %>
                     <%= render "report-scope-destroy", module_scope: module_scope1 %>
                  <% end %>
                <% end %>
              </div>
            </div>

            <!--Scope 2 -->
            <div class="tab-pane fade show" id="scope2" role="tabpanel" aria-labelledby="scope2-tab">
              <div class="flash-modules">
                <% @module_scopes.where(scope: 2).each do |module_scope2| %>
                  <% if ReportScope.new(emission_module_id: module_scope2.id, report_id: params[:report_id]).valid? %>
                    <%= render "report-scope-create", module_scope: module_scope2, report: @report, report_scope: @report_scope %>
                  <% else %>
                   <%= render "report-scope-destroy", module_scope: module_scope2 %>
                  <% end %>
                <% end %>
              </div>
            </div>

            <!--Scope 3 -->
            <div class="tab-pane fade show" id="scope3" role="tabpanel" aria-labelledby="scope3-tab">
              <div class="flash-modules">
                <% @module_scopes.where(scope: 3).each do |module_scope3| %>
                  <% if ReportScope.new(emission_module_id: module_scope3.id, report_id: params[:report_id]).valid? %>
                    <%= render "report-scope-create", module_scope: module_scope3, report: @report, report_scope: @report_scope %>
                  <% else %>
                    <%= render "report-scope-destroy", module_scope: module_scope3 %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>

      </div>
      <div class="selected-modules-container">
        <h5 class="text-center title-module-selection">Your selected modules</h5>
        <%= render "report-scope-add-to-cart" %>
        <%= render "report-scope-next-step" %>
      </div>
    </div>
  </div>
</div>


<!-- Modal affichage des informations détaillées par module  -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle"><%= @module_scopes.last.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= @module_scopes.last.general_description %></p>
        <h5>Emission factor</h5>
        <p> <%= @module_scopes.last.emission_factor_description %></p>
        <h5>Questions</h5>
          <ul>
            <% @module_scopes.last.questions.each do |question| %>
              <p><%= question.content %></p>
            <% end %>
          </ul>
          <% if @module_scopes.last.questions.count == 0 %>
            <p>There are no questions to display yet</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>